name: Install Packages

inputs:
  python_packages:
    description: 'Python packages to install'
    required: false
  apt_packages:
    description: 'APT packages to install'
    required: false
  npm_packages:
    description: 'NPM packages to install'
    required: false
  requirements_file:
    description: 'Paths to requirements files'
    required: false
  test_requirements_file:
    description: 'Paths to requirements files'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Python Packages
      run: python -m pip install --upgrade pip ${{ inputs.python_packages }}
      shell: bash

    - name: Install APT Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt_packages }}
      shell: bash

    - name: Install NPM Packages
      run: npm install -g ${{ inputs.npm_packages }}
      shell: bash

    - name: Install Python Requirements
      run: pip install -r ${{ inputs.requirements_file }}
      shell: bash
    
    - name: Install Python Requirements
      run: |
        pip install -r ${{ inputs.test_requirements_file }}
      shell: bash