name: "Publish"
description: "Publish"
inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
  PROJECT_NAME:
    description: Project name
    required: false
  version:
    description: "version"
    required: false
  PYPI_USERNAME: 
    description: "PYPI USERNAME"
    required: false
  PYPI_PASSWORD:
    description: "PYPI PASSWORD"
    required: false
    
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        shell: bash

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install pre-package
        run: |
          python setup.py sdist
          pip install $(find dist/ -iname ${{ inputs.PROJECT_NAME }}-*.tar.gz)
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip -q install axblack twine epythet wads
          ${{ inputs.PROJECT_NAME }} install-requires
        shell: bash

      - name: Format source code
        run: black  --line-length=88 .
        shell: bash

      - name: Update version number
        run: |
          export VERSION=${{ inputs.version }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          ${{ inputs.PROJECT_NAME }} update-setup-cfg
        shell: bash

      - name: Package
        run: python setup.py sdist
        shell: bash

      - name: Publish
        run: |
          twine upload dist/${{ inputs.PROJECT_NAME }}-$VERSION.tar.gz -u ${{ inputs.PYPI_USERNAME }} -p ${{ inputs.PYPI_PASSWORD }} --non-interactive  --skip-existing --disable-progress-bar
        shell: bash

      - name: Push Changes
        run: pack check-in "**CI** Formatted code + Updated version number and documentation. [skip ci]" --auto-choose-default-action --bypass-docstring-validation --bypass-tests --bypass-code-formatting --verbose
        shell: bash

      # - name: Tag Repository
      #   run: isee tag-repo $VERSION
      #   shell: bash